### PR TITLE
moved onResponse into a anonymous func

### PR DESCRIPTION
**Pull request by staabm**
saves a method call on response.

Will do a benchmark for this change.

### CODE REVIEW

**Comment by kelunik** [comment]
Now we have merge conflicts. :(
But I'm not sure I'll merge this as is, I think we should create that anonymous function in a separate `setup` method or something like that, because otherwise it will make it harder to read.

**Comment by staabm** [comment]
@kelunik just rebased the PR so it merges cleanly again. how would this `setup` method look like then? not sure if it can get more readable as is currently..

**Comment by kelunik** [comment]
It would look like the `ctor`. I just don't like to bloat up `__construct`.
However, it's questionable if this really makes it more readable.

**Comment by staabm** [comment]
@kelunik agree with both points ;). just tell me what you like more, I will do the rest.

**Pull request merged**
