### PR TITLE
Micro optimize call_user_func

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
PS: I realized some TAB vs. SPACES indentations accross the project... @kelunik  whats the expected intendation char?

**Comment by kelunik** [comment]
Tabs except for `.travis.yml`, see https://github.com/amphp/redis/blob/master/.editorconfig

**Comment by kelunik** [comment]
You forgot a `;` here: https://github.com/amphp/redis/pull/13/files#diff-8bfe4c8c460789af5936df0c0ef1830dR14

**Comment by staabm** [comment]
fixed

**Comment by staabm** [comment]
@kelunik could you please check the current prod t@lk instance.. I cannot login atm

**Comment by kelunik** [comment]
Just open the console and copy the error message. Then refresh multiple times. Then post that error into the chat. Please create an issue in `amp-chat` instead next time. ;-)

**Pull request merged**
