### PR TITLE
Inlined doSend to save another func call on hot path

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by kelunik** [comment]
GitHub Streak Extended!

Thanks.

**Comment by staabm** [comment]
@kelunik I also need a repos with which I can extend my streak :)

**Comment by kelunik** [comment]
@staabm you could just contribute to amp-chat. ;-)

**Comment by staabm** [comment]
@kelunik I need a project where other guys contribute and I get the streak for merging PRs :-)

**Comment by kelunik** [comment]
@staabm Just create your real-time data visualization. ;-P

**Comment by staabm** [comment]
@kelunik absolutely. need to take time for that.

Hopefully I will get lots of PRs for that by you ;)

**Pull request merged**
