### PR TITLE
added RespParser benchmark

### PR DESCRIPTION
**Pull request by staabm**
initially created by @kelunik

### CODE REVIEW

**Comment by staabm** [comment]
just to have our small util arround to verify Parser performance

**Comment by kelunik** [comment]
Do we really need that dep here? In my local version, I have an extra loop that does several benchmarks and uses the minimum because of things like CPU on demand profiles.

**Comment by staabm** [comment]
> Do we really need that dep here?

I introduced the lib because I thought it would do the "calibration" etc. for us, but at a closer look it doesnt.
In the past I used https://github.com/polyfractal/athletic which is awesome.

In case we stick only with 1 bench the depth is not worth it, but I introduced it to have a base for even more benchmarks.

For the time beeing you might just commit your self-contained script and we close here, agree?

**Comment by kelunik** [comment]
Yes, I can commit my current `test.php` and rename it to `bench/*.php`. I'll leave this open, because I'll probably do this tomorrow.

**Comment by kelunik** [comment]
https://github.com/amphp/redis/commit/a509af78cd0818c0d19a5a94400e3216c41cd126

**Pull request closed without merging**
